WPEFRAMEWORK_RESOURCECENTER_VERSION = d8e6da01f0a7818d4640348fa299da027e3d6bff
WPEFRAMEWORK_RESOURCECENTER_SITE_METHOD = git
WPEFRAMEWORK_RESOURCECENTER_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_RESOURCECENTER_INSTALL_STAGING = YES
WPEFRAMEWORK_RESOURCECENTER_DEPENDENCIES = WPEFramework

WPEFRAMEWORK_CONF_OPTS += -DBUILDREF_WPEFRAMEWORK=$(shell $(GIT) rev-parse HEAD)

# Other options here are Stub or Westeros
WPEFRAMEWORK_RESOURCECENTER_CONF_OPTS += -DWPEFRAMEWORK_PLUGIN_RESOURCECENTER_IMPLEMENTATION=Nexus

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DEBUG),y)
WPEFRAMEWORK_CONF_OPTS += -DCMAKE_BUILD_TYPE=Debug
endif

$(eval $(cmake-package))
