WPEFRAMEWORK_RESOURCECENTER_VERSION = 05af1f11da54c384afb2bccef03800f9f17084dd
WPEFRAMEWORK_RESOURCECENTER_SITE_METHOD = git
WPEFRAMEWORK_RESOURCECENTER_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_RESOURCECENTER_INSTALL_STAGING = YES
WPEFRAMEWORK_RESOURCECENTER_DEPENDENCIES = WPEFramework

WPEFRAMEWORK_CONF_OPTS += -DBUILDREF_WPEFRAMEWORK=$(shell $(GIT) rev-parse HEAD)

WPEFRAMEWORK_RESOURCECENTER_CONF_OPTS += -DWPEFRAMEWORK_PLUGIN_RESOURCECENTER_IMPLEMENTATION=Nexus

$(eval $(cmake-package))
