################################################################################
#
# gst1-plugins-good
#
################################################################################

KYLIN_GST1_PLUGINS_GOOD_VERSION = 1.8.3
KYLIN_GST1_PLUGINS_GOOD_SOURCE = gst-plugins-good-$(KYLIN_GST1_PLUGINS_GOOD_VERSION).tar.xz
KYLIN_GST1_PLUGINS_GOOD_SITE = https://gstreamer.freedesktop.org/src/gst-plugins-good
KYLIN_GST1_PLUGINS_GOOD_LICENSE_FILES = COPYING
KYLIN_GST1_PLUGINS_GOOD_LICENSE = LGPLv2.1+

KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS = \
	--disable-valgrind \
	--disable-examples \
	--disable-directsound \
	--disable-waveform \
	--disable-sunaudio \
	--disable-osx_audio \
	--disable-osx_video \
	--disable-aalib \
	--disable-aalibtest \
	--disable-libcaca \
	--disable-esd \
	--disable-esdtest


# Options which require currently unpackaged libraries
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += \
	--disable-jack \
	--disable-libdv \
	--disable-dv1394 \
	--disable-shout2

KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES = kylin-gstreamer1 kylin-gst1-plugins-base

ifeq ($(BR2_PACKAGE_LIBV4L),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --with-libv4l2
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += libv4l
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --without-libv4l2
endif

ifeq ($(BR2_PACKAGE_ORC),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-orc
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += orc
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_ALPHA),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-alpha
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-alpha
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_APETAG),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-apetag
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-apetag
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_AUDIOFX),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-audiofx
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-audiofx
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_AUDIOPARSERS),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-audioparsers
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-audioparsers
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_AUPARSE),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-auparse
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-auparse
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_AUTODETECT),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-autodetect
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-autodetect
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_AVI),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-avi
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-avi
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_CUTTER),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-cutter
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-cutter
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_DEBUGUTILS),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-debugutils
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-debugutils
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_DEINTERLACE),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-deinterlace
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-deinterlace
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_DTMF),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-dtmf
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-dtmf
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_EFFECTV),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-effectv
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-effectv
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_EQUALIZER),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-equalizer
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-equalizer
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_FLV),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-flv
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-flv
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_FLX),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-flx
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-flx
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_GOOM),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-goom
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-goom
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_GOOM2K1),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-goom2k1
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-goom2k1
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_ICYDEMUX),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-icydemux
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-icydemux
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_ID3DEMUX),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-id3demux
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-id3demux
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_IMAGEFREEZE),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-imagefreeze
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-imagefreeze
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_INTERLEAVE),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-interleave
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-interleave
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_ISOMP4),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-isomp4
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-isomp4
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_LAW),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-law
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-law
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_LEVEL),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-level
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-level
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_MATROSKA),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-matroska
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-matroska
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_MONOSCOPE),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-monoscope
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-monoscope
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_MULTIFILE),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-multifile
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-multifile
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_MULTIPART),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-multipart
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-multipart
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_REPLAYGAIN),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-replaygain
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-replaygain
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_RTP),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-rtp
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-rtp
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_RTPMANAGER),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-rtpmanager
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-rtpmanager
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_RTSP),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-rtsp
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-rtsp
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_SHAPEWIPE),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-shapewipe
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-shapewipe
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_SMPTE),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-smpte
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-smpte
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_SPECTRUM),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-spectrum
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-spectrum
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_UDP),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-udp
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-udp
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_VIDEOBOX),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-videobox
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-videobox
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_VIDEOCROP),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-videocrop
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-videocrop
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_VIDEOFILTER),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-videofilter
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-videofilter
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_VIDEOMIXER),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-videomixer
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-videomixer
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_WAVENC),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-wavenc
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-wavenc
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_WAVPARSE),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-wavparse
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-wavparse
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_Y4M),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-y4m
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-y4m
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_OSS),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-oss
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-oss
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_OSS4),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-oss4
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-oss4
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_V4L2),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-gst_v4l2
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-gst_v4l2
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_V4L2_PROBE),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-v4l2-probe
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-v4l2-probe
endif

ifeq ($(BR2_PACKAGE_XORG7),y)
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += xlib_libX11 xlib_libXext xlib_libXv
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += \
	--enable-x \
	$(if $(BR2_PACKAGE_XLIB_LIBXFIXES),xlib_libXfixes) \
	$(if $(BR2_PACKAGE_XLIB_LIBXDAMAGE),xlib_libXdamage)
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += \
	--disable-x
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_CAIRO),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-cairo
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += cairo
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-cairo
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_FLAC),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-flac
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += flac
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-flac
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_GDKPIXBUF),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-gdk_pixbuf
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += gdk-pixbuf
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-gdk_pixbuf
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_JPEG),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-jpeg
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += jpeg
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-jpeg
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PNG),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-libpng
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += libpng
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-libpng
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_PULSE),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-pulse
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += pulseaudio
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-pulse
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_SOUPHTTPSRC),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-soup
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += libsoup
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-soup
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_SPEEX),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-speex
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += speex
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-speex
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_TAGLIB),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-taglib
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += taglib
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-taglib
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_VPX),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-vpx
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += libvpx
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-vpx
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_PLUGIN_WAVPACK),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-wavpack
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += wavpack
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-wavpack
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_ZLIB),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-zlib
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += zlib
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-zlib
endif

ifeq ($(BR2_PACKAGE_KYLIN_GST1_PLUGINS_GOOD_BZ2),y)
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --enable-bz2
KYLIN_GST1_PLUGINS_GOOD_DEPENDENCIES += bzip2
else
KYLIN_GST1_PLUGINS_GOOD_CONF_OPTS += --disable-bz2
endif

$(eval $(autotools-package))
