WPEFRAMEWORK_REMOTECONTROL_VERSION = 9fd52291e417ce3cede99b2071060d8b5a067afe
WPEFRAMEWORK_REMOTECONTROL_SITE_METHOD = git
WPEFRAMEWORK_REMOTECONTROL_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_REMOTECONTROL_INSTALL_STAGING = YES
WPEFRAMEWORK_REMOTECONTROL_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

