WPEFRAMEWORK_REMOTECONTROL_VERSION = 4717441eee342b51e9c903ea9d0d395f0cb21db0
WPEFRAMEWORK_REMOTECONTROL_SITE_METHOD = git
WPEFRAMEWORK_REMOTECONTROL_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_REMOTECONTROL_INSTALL_STAGING = YES
WPEFRAMEWORK_REMOTECONTROL_DEPENDENCIES = WPEFramework

WPEFRAMEWORK_CONF_OPTS += -DBUILDREF_WPEFRAMEWORK=$(shell $(GIT) rev-parse HEAD)

$(eval $(cmake-package))

