WPEFRAMEWORK_PROVISIONING_VERSION = 35724ff4896aa11f9858bba7b8054426e0c11cc1
WPEFRAMEWORK_PROVISIONING_SITE_METHOD = git
WPEFRAMEWORK_PROVISIONING_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_PROVISIONING_INSTALL_STAGING = YES
WPEFRAMEWORK_PROVISIONING_DEPENDENCIES = WPEFramework libprovision

$(eval $(cmake-package))

