WPEFRAMEWORK_PROVISIONING_VERSION = 2318fe395541ec7267e4b7f4086924678c4bd3e9
WPEFRAMEWORK_PROVISIONING_SITE_METHOD = git
WPEFRAMEWORK_PROVISIONING_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_PROVISIONING_INSTALL_STAGING = YES
WPEFRAMEWORK_PROVISIONING_DEPENDENCIES = WPEFramework libprovision

WPEFRAMEWORK_PROVISIONING_CONF_OPTS += -DBUILDREF_WPEFRAMEWORK=${WPEFRAMEWORK_PROVISIONING_VERSION}

$(eval $(cmake-package))

