WPEFRAMEWORK_TRACECONTROL_VERSION = d2f48c683ca66bb283aeb9f9bbb9a378186af3a5
WPEFRAMEWORK_TRACECONTROL_SITE_METHOD = git
WPEFRAMEWORK_TRACECONTROL_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_TRACECONTROL_INSTALL_STAGING = YES
WPEFRAMEWORK_TRACECONTROL_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

