WPEFRAMEWORK_WEBSERVER_VERSION = 6fdf3cec1be00af7f739e0734124e9a8c3f04867
WPEFRAMEWORK_WEBSERVER_SITE_METHOD = git
WPEFRAMEWORK_WEBSERVER_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_WEBSERVER_INSTALL_STAGING = YES
WPEFRAMEWORK_WEBSERVER_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

