WPEFRAMEWORK_WEBSERVER_VERSION = 6eeb41a17123070a7f9a122cea8bada0efec95d5
WPEFRAMEWORK_WEBSERVER_SITE_METHOD = git
WPEFRAMEWORK_WEBSERVER_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_WEBSERVER_INSTALL_STAGING = YES
WPEFRAMEWORK_WEBSERVER_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

