WPEFRAMEWORK_NETFLIX_VERSION = f497c4aed868c21e7c0068d11b4006713655a147
WPEFRAMEWORK_NETFLIX_SITE_METHOD = git
WPEFRAMEWORK_NETFLIX_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_NETFLIX_INSTALL_STAGING = YES
WPEFRAMEWORK_NETFLIX_DEPENDENCIES = WPEFramework netflix

$(eval $(cmake-package))

