WPEFRAMEWORK_NETFLIX_VERSION = 1122f9a6ccf69f8c49c812234fabfe95d5986368
WPEFRAMEWORK_NETFLIX_SITE_METHOD = git
WPEFRAMEWORK_NETFLIX_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_NETFLIX_INSTALL_STAGING = YES
WPEFRAMEWORK_NETFLIX_DEPENDENCIES = WPEFramework netflix

$(eval $(cmake-package))

