WPEFRAMEWORK_NETFLIX_VERSION = 9c1a87676781b1c5a17c18416b010cad4c3c672d
WPEFRAMEWORK_NETFLIX_SITE_METHOD = git
WPEFRAMEWORK_NETFLIX_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_NETFLIX_INSTALL_STAGING = YES
WPEFRAMEWORK_NETFLIX_DEPENDENCIES = WPEFramework netflix

WPEFRAMEWORK_NETFLIX_CONF_OPTS += -DBUILDREF_WPEFRAMEWORK=${WPEFRAMEWORK_NETFLIX_VERSION}

$(eval $(cmake-package))

