WPEFRAMEWORK_SWITCHBOARD_VERSION = 1834f11e0577447cb3faed140fd54e0ba728aa57
WPEFRAMEWORK_SWITCHBOARD_SITE_METHOD = git
WPEFRAMEWORK_SWITCHBOARD_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_SWITCHBOARD_INSTALL_STAGING = YES
WPEFRAMEWORK_SWITCHBOARD_DEPENDENCIES = WPEFramework

WPEFRAMEWORK_SWITCHBOARD_CONF_OPTS += -DBUILDREF_WPEFRAMEWORK=${WPEFRAMEWORK_SWITCHBOARD_VERSION}

$(eval $(cmake-package))

