WPEFRAMEWORK_VERSION = 31194dc05898690305eec219a53334987ca96735
WPEFRAMEWORK_SITE_METHOD = git
WPEFRAMEWORK_SITE = git@github.com:Metrological/cppsdk.git
WPEFRAMEWORK_INSTALL_STAGING = YES
WPEFRAMEWORK_DEPENDENCIES = zlib rpi-userland

WPEFRAMEWORK_CONF_OPTS += -DCPPSDK_DEBUG=ON -DINSTALL_HEADERS_TO_TARGET=ON -DCPPSDK_PLATFORM=RPI

define WPEFRAMEWORK_POST_TARGET_INITD
    $(INSTALL) -D -m 0755 package/WPEFramework/S80WPEFramework $(TARGET_DIR)/etc/init.d
    mkdir -p $(TARGET_DIR)/etc/WPEFramework
    $(INSTALL) -D -m 0755 package/WPEFramework/config.json $(TARGET_DIR)/etc/WPEFramework
endef

WPEFRAMEWORK_POST_INSTALL_TARGET_HOOKS += WPEFRAMEWORK_POST_TARGET_INITD

$(eval $(cmake-package))


