WPEFRAMEWORK_VERSION = 804cb4be1df49a301875aa82995cb10a1c28b71e
WPEFRAMEWORK_SITE_METHOD = git
WPEFRAMEWORK_SITE = git@github.com:Metrological/cppsdk.git
WPEFRAMEWORK_INSTALL_STAGING = YES
WPEFRAMEWORK_DEPENDENCIES = zlib

WPEFRAMEWORK_CONF_OPTS += -DCPPSDK_DEBUG=ON -DINSTALL_HEADERS_TO_TARGET=ON 

ifeq ($(BR2_PACKAGE_BCM_REFSW),y)
ifeq ($(BR2_PACKAGE_BCM_REFSW_PLATFORM_7437),y)
WPEFRAMEWORK_CONF_OPTS += -DCPPSDK_PLATFORM=XI5
else ifeq ($(BR2_PACKAGE_BCM_REFSW_PLATFORM_7271),y)
WPEFRAMEWORK_CONF_OPTS += -DCPPSDK_PLATFORM=TCH
else ifeq ($(BR2_PACKAGE_BCM_REFSW_PLATFORM_7250),y)
WPEFRAMEWORK_CONF_OPTS += -DCPPSDK_PLATFORM=EOS
else ifeq ($(BR2_PACKAGE_BCM_REFSW_PLATFORM_7425),y)
WPEFRAMEWORK_CONF_OPTS += -DCPPSDK_PLATFORM=CWC
else ifeq ($(BR2_PACKAGE_BCM_REFSW_PLATFORM_7429),y)
WPEFRAMEWORK_CONF_OPTS += -DCPPSDK_PLATFORM=DWN
else
WPEFRAMEWORK_CONF_OPTS += -DCPPSDK_PLATFORM=NXS
endif
else ifeq ($(BR2_PACKAGE_HORIZON_SDK),y)
WPEFRAMEWORK_CONF_OPTS += -DCPPSDK_PLATFORM=INTELCE
else ifeq ($(BR2_PACKAGE_RPI_FIRMWARE),y)
WPEFRAMEWORK_CONF_OPTS += -DCPPSDK_PLATFORM=RPI
else
WPEFRAMEWORK_CONF_OPTS += -DCPPSDK_PLATFORM=PC_UNIX
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DEBUG),y)
WPEFRAMEWORK_CONF_OPTS += -DCPPSDK_DEBUG=ON
endif

define WPEFRAMEWORK_POST_TARGET_INITD
    $(INSTALL) -D -m 0755 package/WPEFramework/S80WPEFramework $(TARGET_DIR)/etc/init.d
    mkdir -p $(TARGET_DIR)/etc/WPEFramework
    $(INSTALL) -D -m 0755 package/WPEFramework/config.json $(TARGET_DIR)/etc/WPEFramework
endef

WPEFRAMEWORK_POST_INSTALL_TARGET_HOOKS += WPEFRAMEWORK_POST_TARGET_INITD

$(eval $(cmake-package))


