#!/bin/sh

start() {
	echo -n "Starting AMPService: "
        modprobe amp_core
        modprobe gal3d
	start-stop-daemon -S -q -b -m -p /var/run/AMPService.pid --exec /usr/bin/ampservice -- </dev/null >/dev/null 2>&1
	[ $? == 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping AMPService: "
	start-stop-daemon -K -q -p /var/run/AMPService.pid
	[ $? == 0 ] && echo "OK" || echo "FAIL"
	rm -rf /var/run/AMPService.pid
}
restart() {
	stop
	sleep 3
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
