#!/bin/sh

start() {
        echo -n "Starting Bluetooth Daemon: "
        start-stop-daemon -S -q -b -m -p /var/run/bluetoothd.pid --exec /usr/libexec/bluetooth/bluetoothd -- </dev/null >/dev/null 2>&1
        [ $? == 0 ] && echo "OK" || echo "FAIL"
}
stop() {
        echo -n "Stopping Bluetooth Daemon: "
        start-stop-daemon -K -q -p /var/run/bluetoothd.pid
        [ $? == 0 ] && echo "OK" || echo "FAIL"
        rm -rf /var/run/bluetoothd.pid
}
restart() {
        stop
        sleep 3
        start
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart|reload)
                restart
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

exit $?
