WPEFRAMEWORK_WEBPROXY_VERSION = 7f82d4c4fa1f21adbea860d5e8bb983b5294fc91
WPEFRAMEWORK_WEBPROXY_SITE_METHOD = git
WPEFRAMEWORK_WEBPROXY_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_WEBPROXY_INSTALL_STAGING = YES
WPEFRAMEWORK_WEBPROXY_DEPENDENCIES = WPEFramework

WPEFRAMEWORK_CONF_OPTS += -DBUILDREF_WPEFRAMEWORK=$(shell $(GIT) rev-parse HEAD)

$(eval $(cmake-package))

