#!/bin/sh

start() {
	echo -n "Starting udhcpc: "
	start-stop-daemon -S -q -b -m -p /var/run/udhcpc-wlan0.pid --exec /sbin/udhcpc -- -iwlan0 2>&1
	sleep 2
	[ $? == 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping udhcpc: "
	start-stop-daemon -K -q -p /var/run/udhcpc-wlan0.pid
	[ $? == 0 ] && echo "OK" || echo "FAIL"
	rm -rf /var/run/udhcpc.pid
}
restart() {
	stop
	sleep 3
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
