#!/bin/sh      
#              
# Synaptic: enable/disable hdcp service
#              
               
start() {                                                                                          
        echo -n "Disable hdcp: "                                                                
        test_disp hdcp disable
        [ $? == 0 ] && echo "OK" || echo "FAIL"
}       
                                   
stop() {                                               
        echo -n "Enable hdcp: "                    
        test_disp hdcp enable
        [ $? == 0 ] && echo "OK" || echo "FAIL"
}           
            
case "$1" in 
  start)     
        start
        ;;  
  stop)     
        stop     
        ;;       
  restart|reload)
        stop 
        start
        ;;                                   
  *)                                         
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac   
