#!/bin/sh

start() {
        echo -n "Starting Bluetooth Daemon: "
        start-stop-daemon -S -q -b -m -p /var/run/bluetoothd.pid --exec /usr/libexec/bluetooth/bluetoothd -- </dev/null >/dev/null 2>&1
        sleep 2
        /usr/bin/dbus-send --system --type=method_call --dest=org.bluez /org/bluez/hci0 org.freedesktop.DBus.Properties.Set string:org.bluez.Adapter1 string:Powered variant:boolean:false
        sleep 1
        /usr/bin/dbus-send --system --type=method_call --dest=org.bluez /org/bluez/hci0 org.freedesktop.DBus.Properties.Set string:org.bluez.Adapter1 string:Powered variant:boolean:true
        sleep 1
        /usr/bin/hciconfig hci0 sspmode 0
        sleep 1

#        if [ -d /var/lib/bluetooth/*/*:* ]; then
#            echo -n "Waiting for bluetooth device "
#            while [[ ! -e /dev/input/event1 ]] ; do
#                sleep 1;
#            done
#        else
#            echo -n "No bluetooth device paired "
#	fi

        [ $? == 0 ] && echo "OK" || echo "FAIL"
}
stop() {
        echo -n "Stopping Bluetooth Daemon: "
        start-stop-daemon -K -q -p /var/run/bluetoothd.pid
        [ $? == 0 ] && echo "OK" || echo "FAIL"
        rm -rf /var/run/bluetoothd.pid
}
restart() {
        stop
        sleep 3
        start
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart|reload)
                restart
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

exit $?
