#!/bin/sh      
#              
# Start logging
#              
               
SYSLOGD_ARGS=-n                                      
KLOGD_ARGS=-n                                        
[ -r /etc/default/logging ] && . /etc/default/logging
                                   
start() {                                                                                          
        printf "Disable hdcp: "                                                                
        test_disp hdcp disable
        echo "OK"
}       
                                   
stop() {                                               
        printf "Stopping logging: "                    
        test_disp hdcp enable
        echo "OK"
}           
            
case "$1" in 
  start)     
        start
        ;;  
  stop)     
        stop     
        ;;       
  restart|reload)
        stop 
        start
        ;;                                   
  *)                                         
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac   
