WPEFRAMEWORK_DIALSERVER_VERSION = f868253f0f39e01664a6be3dc466f185f5b87336
WPEFRAMEWORK_DIALSERVER_SITE_METHOD = git
WPEFRAMEWORK_DIALSERVER_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_DIALSERVER_INSTALL_STAGING = YES
WPEFRAMEWORK_DIALSERVER_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

