WPEFRAMEWORK_SWITCHBOARD_VERSION = 48574667123c32e405729c45cbaad90bd55e3a10
WPEFRAMEWORK_SWITCHBOARD_SITE_METHOD = git
WPEFRAMEWORK_SWITCHBOARD_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_SWITCHBOARD_INSTALL_STAGING = YES
WPEFRAMEWORK_SWITCHBOARD_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

