WPEFRAMEWORK_SWITCHBOARD_VERSION = a3847a67ebafef37375839dca9298baf90c82844
WPEFRAMEWORK_SWITCHBOARD_SITE_METHOD = git
WPEFRAMEWORK_SWITCHBOARD_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_SWITCHBOARD_INSTALL_STAGING = YES
WPEFRAMEWORK_SWITCHBOARD_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

