WPEFRAMEWORK_SWITCHBOARD_VERSION = b87d9c0ee6f005dac6cdfb33dc0c72a9c2f8b2e4
WPEFRAMEWORK_SWITCHBOARD_SITE_METHOD = git
WPEFRAMEWORK_SWITCHBOARD_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_SWITCHBOARD_INSTALL_STAGING = YES
WPEFRAMEWORK_SWITCHBOARD_DEPENDENCIES = WPEFramework

WPEFRAMEWORK_SWITCHBOARD_CONF_OPTS += -DBUILDREF_WPEFRAMEWORK=${WPEFRAMEWORK_SWITCHBOARD_VERSION}

$(eval $(cmake-package))

