################################################################################
#
# WPEFramework Domotica plugins
#
################################################################################

WPEFRAMEWORK_DOMOTICA_VERSION = 44aa3b349a5487905ecb47f756156a571fa95d5d
WPEFRAMEWORK_DOMOTICA_SITE_METHOD = git
WPEFRAMEWORK_DOMOTICA_SITE = git@github.com:WebPlatformForEmbedded/WPEFrameworkPlugins.git
WPEFRAMEWORK_DOMOTICA_INSTALL_STAGING = YES
WPEFRAMEWORK_DOMOTICA_DEPENDENCIES = wpeframework

WPEFRAMEWORK_DOMOTICA_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_DOMOTICA_VERSION}

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DEBUG),y)
# TODO: This recently stopped working, for now pass debug flags explicitly.
#WPEFRAMEWORK_DOMOTICA_CONF_OPTS += -DCMAKE_BUILD_TYPE=Debug
WPEFRAMEWORK_DOMOTICA_CONF_OPTS += -DCMAKE_CXX_FLAGS='-g -Og'
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DICTIONARY),y)
WPEFRAMEWORK_DOMOTICA_CONF_OPTS += -DPLUGIN_DICTIONARY=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_BUTLER),y)
WPEFRAMEWORK_DOMOTICA_CONF_OPTS += -DPLUGIN_BUTLER=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_IOCONTROL),y)
WPEFRAMEWORK_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_TEMPCONTROL),y)
WPEFRAMEWORK_DOMOTICA_CONF_OPTS += -DPLUGIN_TEMPCONTROL=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_ZWAVECONTROL),y)
WPEFRAMEWORK_DOMOTICA_CONF_OPTS += -DPLUGIN_ZWAVECONTROL=ON
endif

$(eval $(cmake-package))
