WPEFRAMEWORK_DEVICEINFO_VERSION = db7efc8bc8468425767179b1747eed14e97740e1
WPEFRAMEWORK_DEVICEINFO_SITE_METHOD = git
WPEFRAMEWORK_DEVICEINFO_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_DEVICEINFO_INSTALL_STAGING = YES
WPEFRAMEWORK_DEVICEINFO_DEPENDENCIES = WPEFramework

WPEFRAMEWORK_CONF_OPTS += -DBUILDREF_WPEFRAMEWORK=$(shell $(GIT) rev-parse HEAD)

$(eval $(cmake-package))

