#!/bin/sh

#for Debugging
#set -x

WESTON_PATH=/tmp/weston
WESTON_LOG=/tmp/weston.log

start() {
        modprobe dma-buf-test-exporter
	mkdir -p $WESTON_PATH
        chmod 700 $WESTON_PATH
        export XDG_RUNTIME_DIR=$WESTON_PATH
        export LD_LIBRARY_PATH=/usr/lib/server
        # Core dumps
	#ulimit -c unlimited
	echo -n "Starting weston: "
	start-stop-daemon -S -q -b -m -p /var/run/weston.pid --exec /usr/bin/openvt -- -c 2 -s -- /usr/bin/weston --tty=2 --log=$WESTON_LOG --idle-time=0
	[ $? == 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping weston: "
	start-stop-daemon -K -q -p /var/run/weston.pid
	[ $? == 0 ] && echo "OK" || echo "FAIL"
	rm -rf /var/run/weston.pid
}
restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
